### ISSUE TITLE
クリーンアーキテクチャーの勉強

### ISSUE THREAD

**Issue by hiarc** [towase/motting#13]

**Comment by hiarc** [comment]
クラス設計できるレベルの認識合わせ
あまり長くなりすぎない程度に

**Comment by towase** [comment]
https://qiita.com/nrslib/items/a5f902c4defc83bd46b8
https://nrslib.com/clean-architecture/

**Comment by hiarc** [comment]
Qiitaの記事を読み合わせた。
![Untitled - クリーンアーキテクチャの勉強](https://user-images.githubusercontent.com/21194076/115584345-b1516e80-a305-11eb-9338-0d8f750b6874.jpg)
