### ISSUE TITLE
継続的インテグレーションの方法を検討する

### ISSUE THREAD

**Issue by hiarc** [towase/motting#17]

**Comment by hiarc** [comment]
より良い方法を比較検討しましょう
- GitHub Actions
- Circle CI

**Comment by towase** [comment]
# Decision
Github Actionsを使用する。
# Reason
Githubとの親和性が高く、初期設定が不要。
かつ、料金もPublicリポジトリなら無料。

**Comment by hiarc** [comment]
決定したためクローズします。
